name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer
        uses: Artemis-Sera/buildozer-action@v1
        with:
          command: buildozer -v android debug
          subfolder: .

      - name: Upload APK Artifact
        uses: actions/upload-artifacts-action@v3
        with:
          name: app-debug
          path: bin/*.apk
